# Numpy demo

#### Demo, showing major numpy module functionality.

#### Author: Victor Kitov (v.v.kitov@yandex.ru)

In [1]:
%pylab inline  

Populating the interactive namespace from numpy and matplotlib


Previous command loads numpy as np automatically

**Numpy** - math extension module for python. I is most used for fast vector, matrix and multi-dimensional array operations.

# Array initialization

In [2]:
X=array([[1,1],[2,2],[3,3]],dtype=float)
X

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]])

In [3]:
X.dtype

dtype('float64')

In [4]:
X[0,0]=1/3

In [5]:
X

array([[ 0.33333333,  1.        ],
       [ 2.        ,  2.        ],
       [ 3.        ,  3.        ]])

In [6]:
%precision 6

'%.6f'

In [7]:
X[0,0]

0.333333

In [ ]:
Y=array([11,12,13])
Y

## Predefined arrays

In [8]:
zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
ones([3,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [11]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arange(11, 20)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
arange(11, 15, 0.5)

array([ 11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,  14.5])

linspace(start, stop, count) - make uniform grid, consisting of [count] points between [start] and [stop]

In [14]:
linspace(-5,5,100)

array([-5.      , -4.89899 , -4.79798 , -4.69697 , -4.59596 , -4.494949,
       -4.393939, -4.292929, -4.191919, -4.090909, -3.989899, -3.888889,
       -3.787879, -3.686869, -3.585859, -3.484848, -3.383838, -3.282828,
       -3.181818, -3.080808, -2.979798, -2.878788, -2.777778, -2.676768,
       -2.575758, -2.474747, -2.373737, -2.272727, -2.171717, -2.070707,
       -1.969697, -1.868687, -1.767677, -1.666667, -1.565657, -1.464646,
       -1.363636, -1.262626, -1.161616, -1.060606, -0.959596, -0.858586,
       -0.757576, -0.656566, -0.555556, -0.454545, -0.353535, -0.252525,
       -0.151515, -0.050505,  0.050505,  0.151515,  0.252525,  0.353535,
        0.454545,  0.555556,  0.656566,  0.757576,  0.858586,  0.959596,
        1.060606,  1.161616,  1.262626,  1.363636,  1.464646,  1.565657,
        1.666667,  1.767677,  1.868687,  1.969697,  2.070707,  2.171717,
        2.272727,  2.373737,  2.474747,  2.575758,  2.676768,  2.777778,
        2.878788,  2.979798,  3.080808,  3.181818, 

In [15]:
linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [16]:
linspace(0,10,6)

array([  0.,   2.,   4.,   6.,   8.,  10.])

In [17]:
linspace(0,10,3)

array([  0.,   5.,  10.])

Making logarithmic grid

In [18]:
10**linspace(-3,3,7)

array([  1.000000e-03,   1.000000e-02,   1.000000e-01,   1.000000e+00,
         1.000000e+01,   1.000000e+02,   1.000000e+03])

In [19]:
logspace(-3,3,7)

array([  1.000000e-03,   1.000000e-02,   1.000000e-01,   1.000000e+00,
         1.000000e+01,   1.000000e+02,   1.000000e+03])

# Random distributions

In [ ]:
rand(2,3) # uniform U[0,1] distribution

In [ ]:
randn(2,3) # normal N(0,1) istribution

# Mathematic operations

In [ ]:
A=array([[1,2,3],[4,5,6],[7,8,9]])
A

## Operations on single array

#### Operations on two arrays

In [20]:
A=array([[1,2],[3,4]])
B=array([[10,0],[0,10]])

In [21]:
A

array([[1, 2],
       [3, 4]])

In [22]:
B

array([[10,  0],
       [ 0, 10]])

In [23]:
A+B

array([[11,  2],
       [ 3, 14]])

In [24]:
A-B

array([[-9,  2],
       [ 3, -6]])

In [25]:
A*B  # elemenstwise!

array([[10,  0],
       [ 0, 40]])

In [26]:
np.dot(A,B) # matrix multiplication

array([[10, 20],
       [30, 40]])

#### Operations on matrix

In [ ]:
A=array([[1, 2], [3, 4]])
A

In [ ]:
A+10

In [ ]:
10*A

In [ ]:
A%2

In [ ]:
A**2

In [ ]:
2**A

In [ ]:
sqrt(A)

In [ ]:
sin(A)

In [ ]:
A*A  # elementwise multiplication

In [ ]:
np.dot(A,A)  # matrix multiplication

### sum

In [ ]:
A.sum()  # sum of all elements

after *pylab inline* command built-in *sum* function was replaced with numpy *sum*

In [ ]:
np.sum(A)

In [ ]:
sum(A)

In [ ]:
A

In [ ]:
A.sum(0)   # sum along 0-th axis  (along rows)

In [ ]:
sum(A,0)   # sum along 0-th axis  (along rows)

In [ ]:
A.sum(1)   # sum along 1-st axis (along columns) 

In [ ]:
sum(A, 1)   # sum along 1-st axis (along columns) 

In [ ]:
sum(A, axis=1)   # sum along 1-st axis (along columns), more readable

In [ ]:
A

### mean - calculates the average value
### max - calculates maximum
### min - calculates minimum

Work analagous to **sum**

### argmax

In [27]:
a=array([11,12,13,13,12,11])
a

array([11, 12, 13, 13, 12, 11])

In [28]:
ind = argmax(a)  # returns index of the maximum value
a[ind]

13

### maximum

In [29]:
A=[1,20,3,40]
B=[10,2,30,4]

In [30]:
np.maximum(A,B)   # elementwise maximum

array([10, 20, 30, 40])

**minimum** functon works analogous to **maximum**

# shape

Gives the number of dimensions for the array and dimensionality along each dimension

In [31]:
A=array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
A.shape # all dimensions of array A

(2, 3)

In [33]:
len(A) # length along 1st dimension (rows)

2

# Iteration over rows/columns

In [34]:
A=array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
for elem in A:  # iterate rows
    print(elem)

[1 2 3]
[4 5 6]


In [24]:
for elem in A.T:  # iterate columns
    print(elem)

[1 4]
[2 5]
[3 6]


# newaxis

#### 1D vector => 2D Vector-row

In [36]:
A=array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [37]:
A.shape # 1D

(5,)

In [38]:
A=A[:,np.newaxis]

In [39]:
A

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
A.shape

(5, 1)

# reshape

In [41]:
A=arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
A.reshape([3,4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
A.reshape([4,3])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
A.reshape([2,6])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

# Concatenation of arrays

#### hstack - stacks along horizontal direction

In [ ]:
hstack([[1,2,3],[4,5,6],7,[8,9,10,11,12]])

In [ ]:
hstack([eye(3),zeros((3,3))])

#### vstack - stacks along vertical direction

In [ ]:
vstack([[1,2,3],[4,5,6]])

In [ ]:
vstack([eye(3),zeros((3,3))])

# ravel

In [ ]:
A=array([[1,2,3],[3,4,5],[7,8,9]])
A

In [ ]:
B = A.ravel()
B

In [ ]:
B.reshape(A.shape)

### Assignment of arrays

In [ ]:
A=eye(3)
B=A
A[0,0]=100
A

In [ ]:
B

# Boolean operations

In [ ]:
A=arange(11,20)
A

In [ ]:
A>14

In [ ]:
A==14

In [ ]:
A!=14

In [ ]:
A!=4

In [ ]:
A>4

In [ ]:
(A>14) & (A<18)  # elementwise AND

In [ ]:
(A>14) | (A<18)  # elementwise OR

#### any / all

In [ ]:
any([True,True,False])

In [ ]:
all([True,True,False])

In [ ]:
any(A>14)

In [ ]:
A

In [ ]:
A=A.reshape([3,3])
A

In [ ]:
any(A>15)

In [ ]:
all(A<20)

In [ ]:
any(A>14,0)  # any along 0 dimension (rows)

In [ ]:
any(A>14,1)  # any along 1 dimension (columns)

In [ ]:
all(A>14,0)  # all along 0 dimension (rows)

In [ ]:
all(A>14,1)  # all along 1 dimension (columns)

# Indexing

### Boolean indexing

In [ ]:
A=arange(10,20)
A

In [ ]:
A[[2,3,4]]  # integer indexing

In [ ]:
A[A>13]   # boolean indexing

In [ ]:
A[A<18]

In [ ]:
A[(A>13) & (A<18)]

In [ ]:
inds = find(A>14)   # indexes of elements
inds

In [45]:
sels = zeros(len(A),dtype=bool)    # boolean selection of elements
sels[A>14]=True
sels

array([False, False, False, False, False, False, False, False, False,
       False, False, False], dtype=bool)

In [46]:
A[inds]

NameError: name 'inds' is not defined

In [47]:
A[sels]

array([], dtype=int32)

* Boolean indexing - for complex conditioning
* Integer indexing - for subindexing (index(index)), random shuffling

### Convert boolean indexes to integer indexes

In [ ]:
sels = A>13
sels

In [ ]:
inds = find(sels)
inds

In [ ]:
A[sels]

In [ ]:
A[inds]

### Convert integer indexes to boolean indexes

In [ ]:
sels = zeros(len(A), dtype=bool)
sels

In [ ]:
inds=[0,2,4,6,8]

In [ ]:
sels[inds]=True
sels

In [ ]:
A[inds]

In [ ]:
A[sels]

### Random selection

Select randomly 3 elements

In [ ]:
A

In [ ]:
L=arange(len(A))
random.shuffle(L)  # random reordering of sequence, in-place
L

In [ ]:
inds = L[:3]
inds

Select each element with probability 0.1

In [ ]:
A

In [ ]:
u = random.rand(len(A))
u

In [ ]:
u<0.1

In [ ]:
find(u<0.1)

# Slicing

In [ ]:
A=arange(1,16+1).reshape([4,4])
A

In [ ]:
A[:]  # copy of array

In [ ]:
A[2:]

In [ ]:
A[:-2]

In [ ]:
A[:,2:]

In [ ]:
A[:,:-2]

In [ ]:
A[2:,2:]

In [ ]:
A[::2,::2]

# Broadcasting

In [ ]:
A=arange(5)
A

In [ ]:
A=A[:,newaxis]
A

In [ ]:
B=arange(0,50,10)
B

In [ ]:
B=arange(0,50,10)
B=B[newaxis,:]
B

In [ ]:
A+B

In [ ]:
A=array([[1,2,3],[4,5,6]])
A

In [ ]:
B=array([10,20])[:,newaxis]
B

In [ ]:
A+B

In [ ]:
C=array([100,200,300])[newaxis,:]
C

In [ ]:
A+C

In [ ]:
A+1000

# sorting

### Sorting vectors

In [ ]:
a = array([1,2,3,4,3,2,1])
a

In [ ]:
sort(a)  # returns sorted array, not in-place

In [ ]:
inds = argsort(a)  # return indexes which sort the array
a[inds]

### Sorting matrices

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A.sort(0)  # sorts along 0-th dimension (along rows), returns sorted columns, in-place
A

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A.sort(1)  # sorts along 1-st dimension (along rows), returns sorted columns, in-place
A

Get indexes which make the array sorted

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
argsort(A,0)

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
argsort(A,1)

Multidimensional arrays also may be sorted along any dimension

# Unique elements

In [ ]:
A = [0,1,1,2,2,2,3,3,3,3,3,3,3]
A

In [ ]:
u = unique(A)
u

In [ ]:
unique(A, return_counts=True)

In [ ]:
a=arange(-3,3)
a

# Saving memory

In [ ]:
A=eye(100) 

In [ ]:
A.dtype, A.nbytes

In [ ]:
A=A.astype(float32)

In [ ]:
A.dtype, A.nbytes  # two times less memory usage!

In [ ]:
A.dtype

### Sparse matrices

Store only non-zero entries of a matrix. Efficient when the majority of elements are zeroes.

In [ ]:
A

In [ ]:
import scipy
from scipy import sparse
A =  scipy.sparse.dok_matrix(A)

In [ ]:
A.dtype, A.nnz*4  # stores only non-zero elements

# Special values

### nan

nan stands for "not a number". Its value is undefined, and it can mean any number.

In [ ]:
0/0

In [ ]:
float64(0)/float64(0)

In [ ]:
float32(0)/float32(0)

In [ ]:
1/0

In [ ]:
float32(1)/float32(0)

In [ ]:
float32(-1)/float32(0)

In [ ]:
isfinite([1,inf,-inf,nan])

In [ ]:
isinf([1,inf,-inf,nan])

In [ ]:
isnan([1,inf,-inf,nan])

In [ ]:
ind

In [ ]:
A=array([[40,30,20,10],[1,2,3,4],[300,400,100,200]])
A

Learn more:
* [Tutorial on numpy/scipy](http://www.scipy-lectures.org/)
* [Function optimization in scipy](http://www.scipy-lectures.org/advanced/mathematical_optimization/index.html)